# -*- coding: utf-8 -*-
"""Task05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiiQJdcwEFqPqlRpW5LjZWCquNcU2qlQ
"""

def partition(array,low,high):
  pivot=array[high]
  i=low-1
  for j in range(low,high):
    if array[j]<=pivot:
      i+=1
      array[i],array[j]=array[j],array[i]
  array[i+1],array[high]=array[high],array[i+1]
  return i+1

def quicksort(array,low,high):
  if low<high:
    q=partition(array,low,high)
    quicksort(array,low,q-1)
    quicksort(array,q+1,high)
file_in=open('input5.txt','r')
file_out=open('output5.txt','w')
test_case=int(file_in.readline())
nums= list(map(int,file_in.readline().split(' ')))
quicksort(nums,0,test_case-1)
for i in nums:
  if i!=len(nums)-1:
    file_out.write(f'{i} ')
  else:
    file_out.write(f'{i}')
file_out.close()