# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input3.txt','r')
file_out=open('output3.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
ad_list=[[] for i in range(node+1)]
visited_list=[0 for i in range(node+1)]
for i in range(1,edges+1):
  temp=file_in.readline().split(' ')
  ad_list[int(temp[0])].append(int(temp[1]))
def DFS(ad_list,source):
  visited_list[source]=1
  file_out.write(f'{source} ')
  for i in ad_list[source]:
    if visited_list[i]==0:
      DFS(ad_list,i)

source=1
DFS(ad_list,source)
file_out.close()