# -*- coding: utf-8 -*-
"""Task03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiiQJdcwEFqPqlRpW5LjZWCquNcU2qlQ
"""

def devandcon(arr,count=0):
    if len(arr) <= 1:
        return arr,count
    else:
        mid = len(arr)//2
        left = arr[:mid]  # write the parameter
        right = arr[mid:]  # write the parameter
    left_part,left_count=devandcon(left,count)
    right_part,right_count=devandcon(right,count)
    pointer1=0
    pointer2=0
    pointer3=0
    new_list=[0]*(len(left_part)+len(right_part))
    while pointer1<len(left_part) or pointer2<len(right_part):
      if pointer1==len(left_part):
        new_list[pointer3:]=right_part[pointer2:]
        break
      elif pointer2==len(right_part):
        new_list[pointer3:]=left_part[pointer1:]
        break
      elif left_part[pointer1]<right_part[pointer2]:
        new_list[pointer3]=left_part[pointer1]
        pointer1+=1
        pointer3+=1
      elif left_part[pointer1]==right_part[pointer2]:
        new_list[pointer3]=left_part[pointer1]
        pointer3+=1
        new_list[pointer3]=right_part[pointer2]
        pointer1+=1
        pointer2+=1
        pointer3+=1
      else:
        new_list[pointer3]=right_part[pointer2]
        pointer2+=1
        pointer3+=1
        count+= len(left_part) - pointer1
    return new_list,left_count+right_count+count

file_in=open('input3.txt','r')
file_out=open('output3.txt','w')
test_case=int(file_in.readline())
num= list(map(int,file_in.readline().split(' ')))
nums,counter=devandcon(num)
file_out.write(f'{counter}')
file_out.close()