# -*- coding: utf-8 -*-
"""task 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Da0DKhHiadcxmcwULNg04T7p_b2C2BE1
"""

file_in=open('input 04.txt','r')
file_out=open('output 04.txt','w')
total_case=int(file_in.readline())
time=[0]*total_case
total_info=[0]*total_case
name=[0]*total_case
for cases in range(total_case):
  if cases!=total_case-1:
    temp=file_in.readline()[:-1]
  else:
    temp=file_in.readline()
  time[cases]=temp.split()[-1]
  total_info[cases]=temp
  name[cases]=temp.split()[0]
for new in range(total_case):
  for new2 in range(total_case-new-1):
    if name[new2]>name[new2+1]:
      temp_name=name[new2]
      name[new2]=name[new2+1]
      name[new2+1]=temp_name
      temp_info=total_info[new2]
      total_info[new2]=total_info[new2+1]
      total_info[new2+1]=temp_info
    if name[new2]==name[new2+1]:
      if time[new2]>time[new2+1]:
        temp_time=time[new2]
        time[new2]=time[new2+1]
        time[new2+1]=temp_time
        temp_info=total_info[new2]
        total_info[new2]=total_info[new2+1]
        total_info[new2+1]=temp_info
print(total_info)
count=0
for num in range(total_case):
  count+=1
  if count<total_case:
    file_out.write(f'{total_info[num]}\n')
  else:
    file_out.write(f'{total_info[num]} ')
file_out.close()