# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input4.txt','r')
file_out=open('output4.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
parent_list=[i for i in range(node+1)]
ans=[]
ad_list=[(0,0,0) for i in range(node+1)]
for i in range(node+1):
  temp=file_in.readline().split(' ')
  ad_list[i]=((int(temp[0]),int(temp[1]),int(temp[2])))
ad_list.sort(key=lambda ad_list: ad_list[-1])
def root_find(parent_list,city):
  if parent_list[city]==city:
    return parent_list[city]
  else:
    parent_list[city]= root_find(parent_list,parent_list[city])
    return parent_list[city]
def gp(parent_list,city1,city2):
  root1=root_find(parent_list,city1)
  root2=root_find(parent_list,city2)
  if root1!=root2:
    parent_list[root1]=root2
total_cost=0
for j in ad_list:
  city1,city2,cost=j
  root1=root_find(parent_list,city1)
  root2=root_find(parent_list,city2)
  if root1!=root2:
    gp(parent_list,root1,root2)
    total_cost+=cost

file_out.write(f'{total_cost}')
file_out.close()