# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input3.txt','r')
file_out=open('output3.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
parent_list=[i for i in range(node+1)]
size_root=[1 for i in range(node+1)]
ans=[]
def root(x):
  if parent_list[x]==x:
    return parent_list[x]
  else:
    parent_list[x]= root(parent_list[x])
    return parent_list[x]
def gp(one,two):
  one_root=root(one)
  two_root=root(two)
  if one_root==two_root:
    size=size_root[one_root]
  else:
    parent_list[two]=one
    size_root[one_root]+=size_root[two_root]
  ans.append(size_root[one_root])
for i in range(1,edges+1):
  temp=file_in.readline().split(' ')
  gp(int(temp[0]),int(temp[1]))

for i in ans:
  if i!=ans[-1]:
    file_out.write(f'{i}\n')
  else:
    file_out.write(f'{i}')
file_out.close()