# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiiQJdcwEFqPqlRpW5LjZWCquNcU2qlQ
"""

file_in=open('input6.txt','r')
file_out=open('ouput6.txt','w')
test_case=int(file_in.readline())
array=list(map(int,file_in.readline().split(' ')))
def partition(array,low,high):
  pivot=array[high]
  i=low-1
  for j in range(low,high):
    if array[j]<=pivot:
      i+=1
      array[i],array[j]=array[j],array[i]
  array[i+1],array[high]=array[high],array[i+1]
  return i+1

def k_th_smallest_value(array,lowest,highest,k):
    if lowest == highest:
        return array[lowest]
    pos=partition(array,lowest,highest)
    if pos==k:
        return array[k-1]
    elif k<pos:
        return k_th_smallest_value(array,lowest,pos-1,k)
    else:
        return k_th_smallest_value(array,pos+1,highest,k)

query=int(file_in.readline())
for i in range(query):
  k=int(file_in.readline())
  val=k_th_smallest_value(array,0,test_case-1,k)
  if i<query-1:
    file_out.write(f'{val}\n')
  else:
    file_out.write(f'{val}')
file_out.close()