# -*- coding: utf-8 -*-
"""Task02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiiQJdcwEFqPqlRpW5LjZWCquNcU2qlQ
"""

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr)//2
        a1 = mergeSort(arr[:mid])  # write the parameter
        a2 = mergeSort(arr[mid:])  # write the parameter
        if a1<a2:
          max=a2
        else:
          max=a1
        return max

file_in=open('input2.txt','r')
file_out=open('output2.txt','w')
test_case=int(file_in.readline())
list1=list(map(int,file_in.readline().split(' ')))
output=mergeSort(list1)
for i in range(len(output)):
  if i!=len(list1)-1:
    file_out.write(f'{output[i]} ')
  else:
    file_out.write(f'{output[i]}')
file_out.close()