# -*- coding: utf-8 -*-
"""task 01 b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Da0DKhHiadcxmcwULNg04T7p_b2C2BE1
"""

file_in =open('input 01b.txt','r')
file_out=open('output 01b.txt','w')
test= int(file_in.readline())
count=0
for cont in range(test):
  temp= file_in.readline().split(' ')
  if temp[2]=='+':
    count+=1
    if count<test:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])+int(temp[3])}\n')
    else:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])+int(temp[3])}')
  if temp[2]=='-':
    count+=1
    if count<test:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])-int(temp[3])}\n')
    else:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])-int(temp[3])}')
  if temp[2]=='*':
    count+=1
    if count<test:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])*int(temp[3])}\n')
    else:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])*int(temp[3])}')
  if temp[2]=='/':
    count+=1
    if count<test:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])/int(temp[3])}\n')
    else:
      file_out.write(f'Result of {temp[1]} {temp[2]} {int(temp[3])} is {int(temp[1])*int(temp[3])}')
file_out.close()