# -*- coding: utf-8 -*-
"""task 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Da0DKhHiadcxmcwULNg04T7p_b2C2BE1
"""

file_in=open('input 02','r')
file_out=open('output 02','w')
total_elem=file_in.readline()
arr=list(map(int,file_in.readline().split(' ')))
def bubbleSort(arr):
  flag=False
  for i in range(len(arr)-1):
    for j in range(len(arr)-i-1):
      if arr[j] > arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        flag=True
    if flag==False:
      break
  return arr

count=0
for elem in bubbleSort(arr):
  count+=1
  if count<int(total_elem):
    file_out.write(f'{elem} ')
  else:
    file_out.write(f'{elem}')
file_out.close()