# -*- coding: utf-8 -*-
"""Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input6.txt','r')
file_out=open('output6.txt','w')
temp=file_in.readline().split(' ')
row,col=int(temp[0]),int(temp[1])
grid=[[] for i in range(row)]
queue=[]
visited=[[0]*col for i in range(row)]
maximum=0

for i in range(row):
  temp=file_in.readline()
  for j in temp:
    if j!='\n':
      grid[i].append(j)

def diamond(grid,visited,r,c):
  dim=0
  if r<0 or r>=len(grid) or c<0 or c>=len(grid[0]) or visited[r][c]>0 or grid[r][c]=='#':
    return 0
  visited[r][c]=1

  if grid[r][c]=='D':
    dim+=1
  dim+= diamond(grid,visited,r+1,c)
  dim+= diamond(grid,visited,r-1,c)
  dim+= diamond(grid,visited,r,c+1)
  dim+= diamond(grid,visited,r,c-1)
  return dim
for i in range(row):
  for j in range(col):
    if grid[i][j] == '.':
      result=diamond(grid,visited,i,j)
      maximum=max(result,maximum)

file_out.write(f'{maximum}')
file_out.close()