# -*- coding: utf-8 -*-
"""task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C9VUhlC9KbygghfVLsJAeQkT9gZsZo5
"""

file_in=open('input1a.txt','r')
file_out=open('output1a.txt','w')
temp=file_in.readline().split(' ')
total_case=int(temp[0])
sum=int(temp[1])
list_new=[]
list1=list(map(int,file_in.readline().split(' ')))
for i in range(total_case):
  for j in range(i+1,total_case):
    if list1[i]+list1[j]==sum:
      list_new.append(i),list_new.append(j)
if len(list_new)==0:
  file_out.write('IMPOSSIBLE')
else:
  file_out.write(f'{(list_new[-2])+1} {(list_new[-1])+1}')
file_out.close()