# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input3.txt','r')
file_out=open('output3.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
ad_list=[[] for i in range(node+1)]
rev_ad_list=[[] for i in range(node+1)]
visited_list=[0 for i in range(node+1)]
rev_visited_list=[0 for i in range(node+1)]
res=[]
stack=[]
for i in range(1,edges+1):
  temp=file_in.readline().split(' ')
  ad_list[int(temp[0])].append(int(temp[1]))
  rev_ad_list[int(temp[1])].append(int(temp[0]))

def dfs(source):
  visited_list[source]=1
  for j in ad_list[source]:
    if visited_list[j]==0:
      dfs(j)
  stack.append(source)
def rev_dfs(source,res):
  rev_visited_list[source]=1
  for j in rev_ad_list[source]:
    if rev_visited_list[j]==0:
      rev_dfs(j,res)
  res.append(source)
for i in range(1, node+1):
    if visited_list[i]==0:
        dfs(i)
stack.reverse()
for i in stack:
    if rev_visited_list[i]==0:
        res = []
        rev_dfs(i, res)
        ans=''
        for i in res:
          if i!=res[-1]:
            ans+=f'{i} '
          else:
            ans+=f'{i}'
        file_out.write(f'{ans}\n')

file_out.close()