# -*- coding: utf-8 -*-
"""Task 1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input1a.txt','r')
file_out=open('output1a.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
arr=[[0]*(node+1) for i in range(node+1)]
for i in range(edges):
  temp=file_in.readline().split(' ')
  first=int(temp[0])
  arr[first][int(temp[1])]=int(temp[2])
for i in range(len(arr)):
  for j in range(len(arr[i])):
    if j!=(len(arr[i])-1):
      file_out.write(f'{arr[i][j]} ')
    else:
      if i!=(len(arr)-1):
        file_out.write(f'{arr[i][j]}\n')
      else:
        file_out.write(f'{arr[i][j]}')
file_out.close()