# -*- coding: utf-8 -*-
"""task1 a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Da0DKhHiadcxmcwULNg04T7p_b2C2BE1
"""

file_in =open('input 01a.txt','r')
file_out=file_out =open('output 01a.txt','w')
in2=file_in.readlines()
l=list(map(int,in2))
count=0
for num in l[1:]:
  if num%2==0:
    count+=1
    if count<l[0]:
      file_out.write(f'{num} is even \n')
    else:
      file_out.write(f'{num} is even')
  else:
    count+=1
    if count<l[0]:
      file_out.write(f'{num} is odd \n')
    else:
      file_out.write(f'{num} is odd')
file_out.close()