# -*- coding: utf-8 -*-
"""task2b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C9VUhlC9KbygghfVLsJAeQkT9gZsZo5
"""

file_in=open('input2b.txt','r')
file_out=open('output2b.txt','w')
total_case1=int(file_in.readline())
list1=list(map(int,file_in.readline().split(' ')))
total_case2=int(file_in.readline())
list2=list(map(int,file_in.readline().split(' ')))
new_list=[0]*(total_case1+total_case2) #new list size will be addition of len of list1 and list2
pointer1=0 #for the fist list
pointer2=0 #for the 2nd list
pointer3=0 #for the new_list
while pointer1<len(list1) or pointer2<len(list2):
  if pointer1==len(list1): #checking if the pointer has exceeded than the len of list1
    new_list[pointer3:]=list2[pointer2:]
    break
  elif pointer2==len(list2): #checking if the pointer has exceeded than the len of list2
    new_list[pointer3:]=list1[pointer1:]
    break
  elif list1[pointer1]<list2[pointer2]: # checking if list1 val is < than list2 val
    new_list[pointer3]=list1[pointer1] #inserting the value in new list
    pointer1+=1 #increasing first list's pointer value
    pointer3+=1 #increasing new_list pointer value
  elif list1[pointer1]==list2[pointer2]: # checking if list2 val is equal of list1 val
    new_list[pointer3]=list1[pointer1] #inserting the value in new list
    pointer3+=1 #increasing new list's pointer value as both are equal
    new_list[pointer3]=list2[pointer2] #inserting the value in new list as both are equal
    pointer1+=1 #increasing pointer value of list1
    pointer2+=1 #increasing pointer value of list2
    pointer3+=1 #increasing pointer value of new_list
  else: # checking if list2 val is < of list1 val
    new_list[pointer3]=list2[pointer2] #inserting value in new_list
    pointer2+=1 #increasing pointer value of list2
    pointer3+=1 #increasing pointer value of new_list
#for the exact format as sample output
for i in range(len(new_list)):
  if i!=len(new_list)-1:
    file_out.write(f'{new_list[i]} ')
  else:
    file_out.write(f'{new_list[i]}')
file_out.close()