# -*- coding: utf-8 -*-
"""task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Da0DKhHiadcxmcwULNg04T7p_b2C2BE1
"""

file_in=open('input_task 03.txt','r')
file_out=open('output_task 03.txt','w')
total_elem=file_in.readline()
id_list=list(map(int,file_in.readline().split(' ')))
mark_list=list(map(int,file_in.readline().split(' ')))

for num in range(len(mark_list)):
  min_idx=num
  for new in range(num+1,len(mark_list)):
    if mark_list[min_idx]<mark_list[new]:
      min_idx=new
    if mark_list[min_idx]==mark_list[new]:
        if id_list[min_idx]>id_list[new]:
            min_idx=new
  temp_mark=mark_list[num]
  mark_list[num]=mark_list[min_idx]
  mark_list[min_idx]=temp_mark
  temp_id=id_list[num]
  id_list[num]=id_list[min_idx]
  id_list[min_idx]=temp_id
count=0
for val in range(len(mark_list)):
  count+=1
  if count<len(mark_list):
    file_out.write(f'ID: {id_list[val]} Mark: {mark_list[val]}\n')
  else:
   file_out.write(f'ID: {id_list[val]} Mark: {mark_list[val]}')
file_out.close()