# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysf89-b7-MPYQ4HrZ3XnDP9cf4QymiMO
"""

file_in=open('input1.txt','r')
file_out=open('output1.txt','w')
temp=file_in.readline().split(' ')
node,edges=int(temp[0]),int(temp[1])
ad_list=[[] for i in range(node+1)]
distance=[0 for i in range(node+1)]
for i in range(1,edges+1):
  temp=file_in.readline().split(' ')
  ad_list[int(temp[0])].append((int(temp[1]),int(temp[2])))
source= int(file_in.readline())
def dijkstra(ad_list,source):
  queue=[]
  for i in range(1,node+1):
    distance[i]=99999999999999999999999
    queue.append(i)
  distance[source]=0
  while len(queue)!=0:
    min=999999999999999999999999
    u=0
    for j in queue:
      if distance[j]<min:
        min=distance[j]
        u=j
    queue.remove(u)
    for k in ad_list[u]:
      alt=distance[u]+k[1]
      if alt<distance[k[0]]:
        distance[k[0]]=alt
  for i in range(len(distance)):
    if distance[i]==99999999999999999999999:
      distance[i]=-1
dijkstra(ad_list,source)
for i in range(1,(len(distance))):
  if i!=len(distance)-1:
    file_out.write(f'{distance[i]} ')
  else:
    file_out.write(f'{distance[i]}')
file_out.close()