# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19C9VUhlC9KbygghfVLsJAeQkT9gZsZo5
"""

file_in=open('input1b.txt','r')
file_out=open('output1b.txt','w')
temp=file_in.readline().split(' ')
total_case=int(temp[0])
sum=int(temp[1])
list1=list(map(int,file_in.readline().split(' ')))
dict1={}
counter=0
new_list=[] #creating a list to check weather there is a pair or not

for i in range(total_case):
  if list1[i] not in dict1: #checking if the value of list is already in the dict1
    dict1[sum-list1[i]]=i #if not then putting the difference of sum and list1 value as key and index as value
  else:
    new_list.append(dict1[list1[i]]+1),new_list.append(i+1)  #inserting the values of the pair

if len(new_list)==0:
  file_out.write('IMPOSSIBLE') #if the list don't have any pair then the condition of two number making a sum is Impossible
else:
  file_out.write(f'{new_list[0]} {new_list[1]}') #else putting the first pair as output
file_out.close()